### ISSUE TITLE
Aether Portal Loop :: Getting Stuck in Portal

### ISSUE THREAD

**Issue by Lachney** [Modding-Legacy/Aether-Legacy-Rift#11]
Going through the Aether Portal, you can get stuck in a portal loop whether survival or creative

**Comment by CDAGaming** [comment]
This Issue can also cause a crash:
`Caused by: java.lang.RuntimeException: We are asking a region for a chunk out of bound | 1117352 1442552
	at th.c(SourceFile:118) ~[th.class:?]
	at axt.y(SourceFile:45) ~[axt.class:?]
	at th.a_(SourceFile:124) ~[th.class:?]
	at axw.c(SourceFile:350) ~[axw.class:?]
	at aey.a(SourceFile:714) ~[aey.class:?]
	at ayc.a(SourceFile:285) ~[ayc.class:?]
	at bom.b(SourceFile:116) ~[bom.class:?]
	at tv.a(SourceFile:15) ~[tv.class:?]
	at tp.a(SourceFile:35) ~[tp.class:?]
	at bmu.a(SourceFile:95) ~[bmu.class:?]
	at tw.a(SourceFile:62) ~[tw.class:?]
	at tw.a(SourceFile:25) ~[tw.class:?]
	at acr$a.a(SourceFile:130) ~[acr$a.class:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_171]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_171]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) ~[?:1.8.0_171]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_171]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_171]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_171]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_171]`
